---
server:
  port: 10001
application:
  name: bike-web-app
dubbo:
  application:
    name: bike-web-app
  organization: fay
logging:
  config: classpath:logback-spring.xml
bootstrap:
  main:
    class: com.fay.bike.app.BikeWebAppApplication
  check:
    dubbo: true
base:
  name: bike-web-app

---
spring:
  profiles: prod

---
spring:
  profiles: test

